language: python
python:
  - 3.7
  - 3.10
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
  - pip install -r requirements.txt

script:
  - flake8
  - pytest libpythonpro --cov=libpythonpro
after_success:
  - codecov